### ISSUE TITLE
Using auth0 id_token possibly insecure

### ISSUE THREAD

**Issue by dorinclisu** [tokusumi/fastapi-cloudauth#14]
First of all I have to admit that I don't fully grasp all the oauth2 and OIDC concepts, which is probably why I stumbled accross this project to begin with, not knowing how to implement all the details myself.

Anyway, I've been reading auth0 documentation and this source code and I see it's possible to retrieve user email using `Auth0Claims`. But these claims are valid only if FastAPI gets an id_token as Bearer, which is recommended against in this article: https://auth0.com/blog/why-should-use-accesstokens-to-secure-an-api/ that mentions `id_token` is only meant for the client (which I understand is the frontend, not FastAPI).

I would love to find a reason why the official recommendation is not valid in this project.

In my fastapi API I need to know the user email for every request authorization. That's because I support multi-tenancy, where each user has CRUD access only to their own resources. I think this should be a fairly common scenario.. so I'm puzzled why there wouldn't be a straightforward way to do it.

**Comment by jaytarang92** [comment]
@dorinclisu  I guess this is also the reason why I keep getting the scope is not matched error. Since it is not in the id_token. Authentication works but fails when depending on a particular scope. 

![image](https://user-images.githubusercontent.com/12914735/103164528-28e91400-47d2-11eb-9588-9492a6280deb.png)
![image](https://user-images.githubusercontent.com/12914735/103164531-37373000-47d2-11eb-9f74-fea78ff3da4f.png)

**Comment by dorinclisu** [comment]
I ended up implementing my own library https://github.com/dorinclisu/fastapi-auth0
I highly recommend it over this one if auth0.com is the only provider you need.

**Comment by dorinclisu** [comment]
Now to the topic of this issue, `id_token` should indeed not be sent to the API, so the only elegant and performant way to obtain email is the approach I used in my implementation, which is to rely on auth0 rule that adds email claim to `access_token`.

**Comment by tokusumi** [comment]
@dorinclisu Thank you for your very kind advices! (and sorry for really late response 🙇🙇🙇)
I saw your library ✨✨, Literally, it must be much helpful for Auth0 users! (much more than this lib 😅)

I'm planning to document your way as best practice (not default) at first.
And I might make this default, indeed because current version can follow the most of your best practice easily.
